# Generated by Django 4.0.5 on 2022-06-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_booking_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='station',
        ),
        migrations.AddField(
            model_name='booking',
            name='From',
            field=models.CharField(choices=[('Mwiki', 'Mwiki'), ('Maji Mazuri', 'Maji Mazuri'), ('Kamutini', 'Kamutini'), ('Sunton', 'Sunton'), ('Hunters', 'Hunters')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='To',
            field=models.CharField(choices=[('Mwiki', 'Mwiki'), ('Maji Mazuri', 'Maji Mazuri'), ('Kamutini', 'Kamutini'), ('Sunton', 'Sunton'), ('Hunters', 'Hunters')], max_length=50, null=True),
        ),
    ]
